<a href="https://colab.research.google.com/github/alfr-alvarz/cienciadatos-tallerpractico/blob/main/actividad_grupal_1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Link dataset: https://www.kaggle.com/datasets/akshaysehgal/titanic-data-for-data-preprocessing

In [3]:
#importes

import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [9]:
#lectura de csv
df = pd.read_csv('titanic_data.csv')

df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
885,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
886,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
887,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
888,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

- **LIMPIEZA DE DATOS**

In [5]:
datos_faltantes = df.isnull().sum()
print(datos_faltantes)

survived         0
pclass           0
sex              0
age            176
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           686
embark_town      2
alive            0
alone            0
dtype: int64

In [6]:
#datos duplicados

duplicados=df.duplicated().sum()
print(f'Hay {duplicados} datos duplicados')

Hay 107 datos duplicados

In [11]:
#outliers

outliers=

         survived      pclass         age       sibsp       parch        fare
count  889.000000  889.000000  713.000000  889.000000  889.000000  889.000000
mean     0.384702    2.307087   29.698696    0.523060    0.382452   32.259059
std      0.486799    0.836367   14.536691    1.103729    0.806761   49.735870
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.000000    0.000000    0.000000    7.925000
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [12]:
df_limpieza = df.copy() #copiar el dataframe a una version trabajable para preservar el original

In [13]:
df_limpieza = df_limpieza.drop_duplicates() #funcion la cual borra las filas duplicadas
df_limpieza

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
885,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
886,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
887,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
888,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [14]:
df_limpieza['age'] = df_limpieza['age'].fillna(df_limpieza['age'].mean()) #funcion la cual reemplaza las edades faltantes por la media de las edades
df_limpieza

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,3,female,39.000000,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
885,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
886,0,3,female,29.869158,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
887,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
888,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [17]:
media_fare = df_limpieza['fare'].mean() #Media de los pasajes

desv_estandar_fare= df_limpieza['fare'].std() #Desviacion estandar de los pasajes

cut_off = desv_estandar_fare * 3 #medida de corte

lower, upper = media_fare - cut_off, desv_estandar_fare + cut_off #definir corte superior e inferior, 3 STD hacia arriba 3 STD hacia abajo

df_limpieza2 = df_limpieza[(df_limpieza['fare'] > lower) & (df_limpieza['fare'] < upper)]

df_limpieza2

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,3,female,39.000000,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
885,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
886,0,3,female,29.869158,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
887,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
888,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True